Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Carbon.CodeEditor:Plugin':
            resource: 'resource://Carbon.CodeEditor/Public/Plugin/esm-plugin.loader.js'
            position: 'before Neos.Neos.UI:Vendor'
        stylesheets:
          'Carbon.CodeEditor:Plugin':
            resource: 'resource://Carbon.CodeEditor/Public/Plugin/Plugin.css'

      frontendConfiguration:
        'Carbon.CodeEditor':
          clientTailwindConfig: "${Configuration.setting('Carbon.CodeEditor.clientTailwindConfig')}"
