Neos:
  Flow:
    mvc:
      routes:
        Carbon.CodePen: true
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Carbon.CodePen:backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Carbon\CodePen\Controller\.*'
  Neos:
    fusion:
      autoInclude:
        "Carbon.CodePen": true

    Ui:
      resources:
        javascript:
          'Carbon.CodePen:Plugin':
            resource: 'resource://Carbon.CodePen/Public/Plugin/Plugin.js'
            attributes:
              type: "module"
        stylesheets:
          'Carbon.CodePen:Plugin':
            resource: 'resource://Carbon.CodePen/Public/Plugin/Plugin.css'
