Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Carbon.CodePen:Plugin':
            resource: 'resource://Carbon.CodePen/Public/Plugin/Plugin.js'
            # TODO add `type` option in Neos ui
            type: 'module'
        stylesheets:
          'Carbon.CodePen:Plugin':
            resource: 'resource://Carbon.CodePen/Public/Plugin/Plugin.css'

      frontendConfiguration:
        'Carbon.CodePen':
          tailwindcss:
            enabled: true
            workerUri: "${StaticResource.uri('Carbon.CodePen', 'Public/extensibletailwind.worker.js')}"
            clientConfig: null
