Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Carbon.CodeEditor:Plugin':
            resource: 'resource://Carbon.CodeEditor/Public/Plugin/Plugin.js'
            # TODO add `type` option in Neos ui
            type: 'module'
        stylesheets:
          'Carbon.CodeEditor:Plugin':
            resource: 'resource://Carbon.CodeEditor/Public/Plugin/Plugin.css'

      frontendConfiguration:
        'Carbon.CodeEditor':
          clientTailwindConfig: "${Configuration.setting('Carbon.CodeEditor.clientTailwindConfig')}"
