Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Carbon.CodeEditor:Plugin':
            resource: 'resource://Carbon.CodeEditor/Public/Plugin/Plugin.js'

      frontendConfiguration:
        'Carbon.CodeEditor':
          MonacoEditorInclude: ${StaticResource.uri('Carbon.CodeEditor', 'Public/Monaco/index.js')}
          clientTailwindConfig: "${Configuration.setting('Carbon.CodeEditor.clientTailwindConfig')}"
