Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Carbon.CodeEditor':
          tailwindcss:

            #
            # Enable Tailwind css support for the monaco editor.
            #
            # @var boolean
            #
            enabled: true

            #
            # Uri for the worker to be used.
            # Its possible to configure this to a custom worker with embedded Tailwind config.
            # This way plugins from the tailwind config are preserved.
            #
            # @var string
            #
            workerUri: "${StaticResource.uri('Neos.Demo', 'Public/embeddedconfigtailwind.worker.js')}"

            #
            # To be used with the *default worker* implementation.
            # A simple way to provide config as json.
            # Plugins (eg functions) of the tailwind config cannot not be preserved.
            #
            # @var string?
            #
            clientConfig: "${File.readFile('resource://Neos.Demo/Public/clientTailwindConfig.json')}"
