name: Build Javascript

on:
  workflow_dispatch:
  push:
    paths:
      - "Resources/Private/Plugin/**/*.ts"
      - "Resources/Private/Plugin/**/*.tsx"
    branches-ignore:
      - dependabot/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: Resources/Private/Plugin/.nvmrc
          cache: pnpm
          cache-dependency-path: Resources/Private/Plugin/pnpm-lock.yaml

      - name: Build JS and CSS
        run: pnpm -C Resources/Private/Plugin pipeline

      - name: Push files to GitHub
        run: |
          set +e
          git status -s | grep Resources/Public
          if [ $? -eq 0 ]
          then
              set -e
              git config --global user.name "github-actions[bot]"
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add -f Resources/Public
              git commit -m "Update: Build frontend files"
              git push
          else
              set -e
              echo "No changes since last run"
          fi
